describe('Test rundown', () => {
  beforeEach(() => {
    cy.visit('/rundown/G6xVUpdg91LOM2Hx2Dv4NpJFuaw_') 
  })
  it('successfully loads', () => {
    cy.get('.sofie-logo').should('be.visible')
    cy.get('.rundown-name')
      .should('be.visible')
      .should('contain.text', 'XPRO')
    cy.get('.mos > .indicator__tooltip').should('not.be.visible')
    cy.get('.mos > .indicator__tooltip')
      .invoke('css', 'display', 'block')
      .then(() => {
        cy.wait(500)
        cy.get('.mos > .indicator__tooltip').should('be.visible')
      })
      .invoke('css', 'display', 'none')
  })
  it('header looks ok', () => {
    cy.get('.first-row').should('be.visible')
    cy.get('.col > .rundown__overview')
      .should('be.visible')
      .children()
      .should('have.length.greaterThan', 1)
  })
  it('timeline looks OK', () => {  
    cy.get('.segment-timeline-container')
      .children()
      .should('have.length.greaterThan', 1)
  })
  it('status bar looks ok', () => {
    cy.get('.status-bar')
      .children().first().children()
      .as('status')
      .first()
      .should('be.visible')
      .click()
      .click()

    cy.get('@status')
      .first().next()
      .should('be.visible')
      .click()
    
    cy.get('@status')
      .first().next().next()
      .should('be.visible')
      .should('contain.text', 'F11')
      .should('contain.text', 'Fullscreen')
      .click()

    cy.get('.support-pop-up-panel')    
     .should('not.be.visible')

    cy.get('@status')
      .last()
      .as('helpButton')
      .should('be.visible')
      .click()

    cy.get('.support-pop-up-panel').should('be.visible')
    cy.get('@helpButton').click()
    cy.get('.support-pop-up-panel').should('not.be.visible')
  })
  it('has evaluation', () => {
    cy.contains('Evaluation')
      .scrollIntoView()
    cy.get('select.form-control')
      .select('minor')
      .should('contain.text', 'didn\'t')
    cy.get('textarea.form-control')
      .type('Cypress typed this evaluation.{enter}Look how Cypress types.{enter}Letter-by-letter.')
    cy.get('input.form-control')
      .type('Cypress.io')
  })
})